# Generated by Django 3.0.4 on 2020-03-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urldata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('domain_name', models.CharField(db_column='Domain_Name', max_length=30)),
                ('creation_date', models.DateTimeField(db_column='Creation_Date')),
                ('organization', models.CharField(blank=True, db_column='Organization', max_length=30, null=True)),
            ],
            options={
                'db_table': 'UrlData',
                'managed': False,
            },
        ),
    ]
